__author__ = 'matthew'

import sys,os.path

def main(path):
  if os.path.isfile(path):
    with open(path) as f:
      for line in f:
        print(line.split('\t'))

  tshark_fields = ['frame.time_epoch',
                   'tcp.analysis.bytes_in_flight',
                   'tcp.flags',
                   'tcp.out_of_order',
                   'tcp.reused_ports',
                   'tcp.checksum',
                   'tcp.checksum_bad',
                   'tcp.checksum_good',
                   'tcp.len',
                   'tcp.hdr_len',
                   'tcp.nxtseq',
                   'tcp.options',
                   'tcp.optins.scps',
                   'tcp.wscale.multiplier',
                   'tcp.wscale.shift',
                   'tcp.pdu.size',
                   'tcp.pdu.time',
                   'tcp.proc.dstcmd',
                   'tcp.proc.srccmd',
                   'tcp.segment',
                   'tcp.seq',
                   'tcp.stream',
                   'tcp.time_delta',
                   'ip.proto',
                   'ip.src',
                   'ip.dst',
                   'ip.ttl',
                   'tcp.dstport',
                   'tcp.srcport',
                   'ip.checksum',
                   'ip.checksum_good',
                   'ip.checksum_bad',
                   'ip.fragment.count',
                   'ip.fragment.toolongfragment',
                   'ip.hdr_len',
                   ]
  field_names = ['epoch',
                 'bytes_in_flight',
                 'flags',
                 'out_of_order',
                 'reused_ports',
                 'tcp_checksum',
                 'tcp_checksum_bad',
                 'tcp_checksum_good',
                 'tcp_len',
                 'tcp_hdr_len',
                 'nxtseq',
                 'options',
                 'options_scps',
                 'wscale_multiplier',
                 'wscale_shift',
                 'pdu_size',
                 'pdu_time',
                 'proc_dstcmd',
                 'proc_srccmd',
                 'segment',
                 'seq',
                 'stream',
                 'time_delta',
                 'protocol',
                 'sip',
                 'dip',
                 'ttl',
                 'dport',
                 'sport',
                 'ip_checksum',
                 'ip_checksum_good',
                 'ip_checksum_bad',
                 'ip_fragment_count',
                 'ip_fragment_toolongfragment',
                 'ip_hdr_len',
                 ]

if __name__=="__main__": main(sys.argv[1:])